# task-job.crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: taskjobs.kubernetes.tjob.com
spec:
  group: kubernetes.tjob.com
  names:
    kind: TaskJob
    listKind: TaskJobList
    plural: taskjobs
    singular: taskjob
    shortNames:
    - tj
    - task
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                jobName:
                  type: string
                state:
                  type: string
                  enum:
                    - Pending
                    - Running
                    - Completed
                    - Failed
                jobParams:
                  type: object
                  additionalProperties:
                    type: string
                image:
                  type: string
                imagePullPolicy:
                  type: string
                  enum:
                    - Always
                    - IfNotPresent
                    - Never
                replicas:
                  type: integer
            status:
              type: object
              properties:
                state:
                  type: string
                completionTime:
                  type: string
                  format: date-time
      subresources:
        status: {}
