name: Build and Deploy TaskJob Controller to Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Deploy Controller to Minikube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Build controller image
        run: |
          docker build -t task-job-controller:${{ github.sha }} .

      - name: Export controller image
        run: |
          docker save task-job-controller:${{ github.sha }} -o task-job-controller-${{ github.sha }}.tar

      - name: Build task-job image
        run: |
          docker build -t task-job ./task-job-service

      - name: Export task-job image
        run: |
          docker save task-job -o task-job.tar

      # Set Minikube
      - name: Run Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube /usr/local/bin/
          sudo chmod +x /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Load images into Minikube
        run: |
          minikube image load task-job-controller-${{ github.sha }}.tar
          minikube image load task-job.tar

      - name: Replace controller image tag
        run: |
          IMAGE_TAG="task-job-controller:${{ github.sha }}"
          sed -i "/image:/s|task-job-controller|$IMAGE_TAG|g" k8s/controller-deployment.yaml

      # Deploy the controller to Minikube
      - name: Deploy resources to Minikube
        run: |
          kubectl apply -f k8s/crd.yaml
          kubectl apply -f k8s/controller-deployment.yaml
          kubectl apply -f k8s/task-job.yaml

      - name: Verify controller image in Minikube
        run: |
          minikube ssh -- docker images

      - name: Check Minikube resources
        run: |
          minikube ssh -- free -h
          minikube ssh -- df -h

      # Verify controller is working
      - name: Check task-job deployment
        run: |
          kubectl get pods --namespace=default
          kubectl logs -l app=task-job --namespace=default
