name: Build and Deploy TaskJob Controller to Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Deploy Controller to Minikube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      # Set Minikube
      - name: Start Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube /usr/local/bin/
          sudo chmod +x /usr/local/bin/minikube
          minikube start --driver=docker --container-runtime=docker

      # Build images
      - name: Build controller image
        run: |
          eval $(minikube docker-env)
          docker build -t task-job-controller:latest .

      - name: Build task-job service image
        run: |
          eval $(minikube docker-env)
          docker build -t task-job:latest ./task-job-service

      - name: Deploy CRD and controller
        run: |
          kubectl apply -f k8s/crd.yaml
          kubectl apply -f k8s/controller-deployment.yaml

      - name: Deploy TaskJob
        run: |
          kubectl apply -f k8s/task-job.yaml

      - name: Verify controller image in Minikube
        run: |
          minikube ssh -- docker images

      - name: Check Minikube resources
        run: |
          minikube ssh -- free -h
          minikube ssh -- df -h

      - name: Verify pods
        run: |
          kubectl get pods -n default
          kubectl logs -l app=task-job-controller -n default
          kubectl logs -l app=task-job -n default
